"""rename department

Revision ID: 984c53754887
Revises: d372e7fde513
Create Date: 2025-06-14 08:40:12.242321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984c53754887'
down_revision = 'd372e7fde513'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###

